// src/app/header/header.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { select, Store } from '@ngrx/store';
import * as config from 'app/app.config';
import { ToggleSidebarAction } from 'app/store/actions/core.actions';
import { AppState } from 'app/store/reducers';
import * as fromAuthReducer from 'app/store/reducers/auth.reducer';
import { sidebarCollapsed } from 'app/store/reducers/core.reducer';
import { AppUser, Nullable } from 'app/types';
import { Observable } from 'rxjs';
import { LogoutAction } from '../store/actions/auth.actions';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  encapsulation: ViewEncapsulation.None,
})
export class HeaderComponent {
  sidebarCollapsed$: Observable<boolean>;
  user$: Observable<Nullable<AppUser>>;
  signedIn$: Observable<boolean>;
  isNavCollapsed = true;
  isAccountMenuCollapsed = true;

  c = config;

  constructor(private store: Store<AppState>) {
    this.sidebarCollapsed$ = this.store.pipe(select(sidebarCollapsed));
    this.user$ = this.store.pipe(select(fromAuthReducer.data));
    this.signedIn$ = this.store.pipe(select(fromAuthReducer.signedIn));
  }

  toggleSidebar() {
    this.store.dispatch(new ToggleSidebarAction(null));
  }

  toggleAccountMenu() {
    this.isAccountMenuCollapsed = !this.isAccountMenuCollapsed;
    if (!this.isNavCollapsed)
      this.isNavCollapsed = true;
  }

  toggleNav() {
    this.isNavCollapsed = !this.isNavCollapsed;
    if (!this.isAccountMenuCollapsed)
      this.isAccountMenuCollapsed = true;
  }

  toggleNavs(collapsed: boolean) {
    this.isNavCollapsed = collapsed;
    this.isAccountMenuCollapsed = collapsed;
  }

  logout() {
    this.toggleNavs(true);

    this.store.dispatch(new LogoutAction());
  }
}

<ng-container *appVar="signedIn$ | async as signedIn">
  <nav class="navbar sticky-top navbar-dark bg-primary navbar-expand-lg" *appVar="user$ | async as user">
    <!-- Step 3: Toggle the value of the property when the toggler button is clicked. -->
    <button class="navbar-toggler" id="account-menu-toggler" type="button" (click)="toggleAccountMenu()">
      <span class="sr-only">{{'GLOBAL.HEADER.ACCOUNT_MENU' | translate}}</span>
      <app-avatar-wrap [avatarUrl]="user.avatarUrl" [avatarProvider]="user.avatarProvider" [size]="40"></app-avatar-wrap>
    </button>

    <span class="navbar-brand d-lg-none">MLP Vector Club</span>

    <!-- Step 3: Toggle the value of the property when the toggler button is clicked. -->
    <button class="navbar-toggler" type="button" (click)="toggleNav()">
      <i class="fa fa-fw" [class.fa-bars]="isNavCollapsed" [class.fa-times]="!isNavCollapsed"></i>
    </button>

    <div [ngbCollapse]="isAccountMenuCollapsed" class="collapse navbar-collapse" id="account-menu">
      <ul class="navbar-nav">
        <li class="nav-item">
          <span class="nav-link active">
            <app-user-link *ngIf="signedIn; else defaultUsername" [userName]="user.name"></app-user-link>
            <ng-template #defaultUsername>
              {{'GLOBAL.GUEST_USER_NAME' | translate}}
            </ng-template>
            <small class="d-block text-uppercase">{{user.role | roleLabel}}</small>
          </span>
        </li>
        <li *ngIf="signedIn" class="nav-item">
          <a #logoutTrigger="ngbPopover" class="nav-link" [popoverTitle]="'GLOBAL.CONFIRM_POPOVER.TITLE' | translate" [ngbPopover]="logoutConfirm" placement="bottom">{{'GLOBAL.HEADER.LOGOUT' | translate}}</a>
          <ng-template #logoutConfirm>
            <button class="btn btn-primary" (click)="logoutTrigger.close(); logout()">{{'GLOBAL.CONFIRM_POPOVER.YES' | translate}}</button>
            <button class="btn btn-light" (click)="logoutTrigger.close()">{{'GLOBAL.CONFIRM_POPOVER.NO' | translate}}</button>
          </ng-template>
        </li>
        <li *ngIf="!signedIn" class="nav-item">
          <a class="nav-link">{{'GLOBAL.HEADER.LOGIN' | translate}}</a>
        </li>
      </ul>
    </div>

    <!-- Step 2: Add the ngbCollapse directive to the element below. -->
    <div [ngbCollapse]="isNavCollapsed" class="collapse navbar-collapse">
      <ul class="navbar-nav" drag-scroll>
        <li class="nav-item">
          <a class="nav-link" routerLink='/episode/latest'>{{'TITLES.LATEST_EPISODE' | translate}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLink='/show'>{{'TITLES.SHOW' | translate}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLink='/cg'>{{'TITLES.COLOR_GUIDE' | translate}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLink='/events'>{{'TITLES.EVENTS' | translate}}</a>
        </li>
        <ng-container *ngIf="signedIn">
          <li class="nav-item">
            <app-user-link [userName]="user.name" [text]="'TITLES.ACCOUNT' | translate"></app-user-link>
          </li>
        </ng-container>
        <ng-container *ngIf="user.role | permission:'staff'">
          <li class="nav-item">
            <a class="nav-link" routerLink='/users'>{{'TITLES.USERS' | translate}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink='/admin'>{{'TITLES.ADMIN' | translate}}</a>
          </li>
        </ng-container>
        <li class="nav-item">
          <a class="nav-link" routerLink='/about'>{{'TITLES.ABOUT' | translate}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" [href]="c.CLUB_URL" target="_blank" rel="noopener">
            MLP-VectorClub
            <i class="fa fa-external-link-alt"></i>
          </a>
        </li>
      </ul>
    </div>
  </nav>
</ng-container>

// src/components/Header.tsx
import { Collapse, Nav, Navbar, NavbarBrand, NavbarToggler, NavItem, NavLink } from 'reactstrap';
import Link from 'next/link';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { useDispatch, useSelector } from 'react-redux';
import ScrollContainer from 'react-indiana-drag-scroll';
import { CLUB_URL } from '../config';
import { permission } from '../utils';
import ExternalLink from './shared/ExternalLink';
import { WithTFunction } from '../types';
import { RootState } from '../store/rootReducer';
import { coreActions } from '../store/slices';

export default (({ t }) => {
  const { user } = useSelector((state: RootState) => state.auth);
  const { sidebarOpen } = useSelector((state: RootState) => state.core);
  const dispatch = useDispatch();

  const toggleSidebar = () => dispatch(coreActions.toggleSidebar(!sidebarOpen));

  return (
    <ScrollContainer>
      <Navbar expand="lg" sticky="top" dark className="bg-primary">
        <NavbarToggler id="account-menu-toggler" onClick={toggleSidebar}>
          <FontAwesomeIcon icon={sidebarOpen ? 'bars' : 'times'} />
        </NavbarToggler>

        <NavbarBrand className="d-lg-none">MLP Vector Club</NavbarBrand>

        <Collapse navbar isOpen>
          <Nav navbar>
            <NavItem>
              <Link href="/cg" passHref>
                <NavLink>{t('titles.colorGuide')}</NavLink>
              </Link>
            </NavItem>
            <NavItem>
              <Link href="/show" passHref>
                <NavLink>{t('titles.show')}</NavLink>
              </Link>
            </NavItem>
            <NavItem>
              <Link href="/events" passHref>
                <NavLink>{t('titles.events')}</NavLink>
              </Link>
            </NavItem>
            {permission(user.role, 'staff') && (
              <NavItem>
                <Link href="/admin" passHref>
                  <NavLink>{t('titles.admin')}</NavLink>
                </Link>
              </NavItem>
            )}
            <NavItem>
              <Link href="/about" passHref>
                <NavLink>{t('titles.about')}</NavLink>
              </Link>
            </NavItem>
            <NavItem>
              <ExternalLink className="nav-link" href={CLUB_URL}>
                MLP-VectorClub
                <FontAwesomeIcon icon="external-link-alt" />
              </ExternalLink>
            </NavItem>
          </Nav>
        </Collapse>
      </Navbar>
    </ScrollContainer>
  );
}) as React.FC<WithTFunction>;
