// apps/celestia/src/components/shared/AvatarWrap.tsx
import { memo, VFC } from 'react';
import classNames from 'classnames';
import { AvatarProvider, Nullable, VectorApp } from 'src/types';
import { GUEST_AVATAR } from 'src/config';
import Image from 'next/image';

interface PropTypes {
  avatarUrl: Nullable<string>;
  avatarProvider: AvatarProvider;
  email?: Nullable<string>;
  emailHash?: Nullable<string>;
  size: number;
  className?: string;
  vectorApp?: VectorApp | null;
}

const AvatarWrap: VFC<PropTypes> = ({ avatarProvider, avatarUrl, size, className, vectorApp = null }) => (
  <div className={classNames(`avatar-wrap provider-${avatarProvider}`, className, vectorApp && `app-${vectorApp}`)}>
    <Image src={avatarUrl || GUEST_AVATAR} className="avatar" width={size} height={size} unoptimized priority alt="Avatar image" />
  </div>
);

export default memo(AvatarWrap);

// src/app/shared/components/avatar-wrap.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import { GUEST_AVATAR } from 'app/app.config';
import { AvatarProvider, Nullable } from 'app/types';

@Component({
  selector: 'app-avatar-wrap',
  templateUrl: './avatar-wrap.component.html',
  encapsulation: ViewEncapsulation.None,
})
export class AvatarWrapComponent {

  @Input()
  avatarUrl: Nullable<string>;

  @Input()
  avatarProvider: AvatarProvider;

  @Input()
  size: number;

  guestAvatar = GUEST_AVATAR;

}

<div [class]="'avatar-wrap provider-' + avatarProvider">
  <img [src]="avatarUrl || guestAvatar" class="avatar" [ngStyle]="{'width':size+'px', 'height':size+'px'}">
</div>
